### ISSUE TITLE
use vite or webpack without react-scripts please 

### ISSUE THREAD

**Issue by NovaStream2030** [vladyoslav/vk-mini-apps-template#1]

**Comment by kosheeta** [comment]
Полностью поддерживаю, написал в поддержку с точно таким же запросом, сказали написать на гит, а тут вот как раз уже есть такой запрос. Ибо сейчас пытаюсь создать новый проект с большим количеством рекламы за награду и вынужден бороться с долгим запуском `react-scripts`, который эмитирует мне загрузку.

**Comment by vladyoslav** [comment]
Принято, темплейт теперь использует Vite.
